apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator
  labels:
    app: password-generator
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: password-generator
  template:
    metadata:
      labels:
        app: password-generator
    spec:
      containers:
      - name: password-generator
        image: gillvarghesesajan/password-generator:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 180
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 180
          periodSeconds: 60
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"          

