apiVersion: v1
kind: Service
metadata:
  labels:
    app: password-generator
  name: password-generator
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: password-generator
  type: NodePort

